version: "3.9"

services:
  nginx:
    build: ./Nginx
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:8080:8080
    networks:
      - mynet
    depends_on:
      - client
      - api
  client:
    build: ./Website
    ports:
      - 3001:3000
    networks:
      - mynet
    depends_on:
      - api
  api:
    build: ./Backend
    ports:
      - 8081:8080
    networks:
      - mynet
volumes:
  volumedb:

networks:
  mynet:
